name: Deploy to VPS

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CLASSIC_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Deploy to production - ${{ github.event.head_commit.message }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/projects/autotrendz_backend
          git pull
          docker compose pull
          docker compose up -d
